language: c

os:
  - linux
  - osx
  - windows

sudo: false

services:
  - xvfb

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install tox-conda

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb=xvfb-run; fi
  - $xvfb tox