language: c

os:
  - linux
  - osx
  - windows

sudo: false

env:
  - PYTHON_VERSION=3.7
  - PYTHON_VERSION=3.6

services:
  - xvfb

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install tox-conda tox-travis

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb=xvfb-run; fi
  - $xvfb tox