language: c

os:
  - linux
  - osx

sudo: false

env:
  global:
    - SETUP_XVFB=True
    - PIP_DEPENDENCIES="tox-conda tox-travis"
  matrix:
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.6

services:
  - xvfb

install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - tox