environment:
  global:
    - CODACY_PROJECT_TOKEN: "c0ef4a117d424aa592e5ef2328b11a3a"
  matrix:
    - PYTHON_TARGET: "3.7"
    - PYTHON_TARGET: "3.6"

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - conda create -q -n test-environment python=%PYTHON_TARGET% openbabel rdkit -c openbabel -c conda-forge
  - activate test-environment
  - pip install pytest-sugar pytest-cov coveralls codecov>=1.4.0 codacy-coverage

build: false

test_script:
  - pytest --pyargs reacnetgenerator --cov {envsitepackagesdir}/reacnetgenerator -s
  - coveralls
  - codecov -e TOXENV
  - python-codacy-coverage -r coverage.xml
