environment:
  matrix:
    - TOX_ENV: "py37"
    - TOX_ENV: "py36"

platform:
  - x64

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - pip install tox-conda

build: false

test_script:
  - tox -e %TOX_ENV%