environment:
  COVERALLS_REPO_TOKEN:
    secure: vSFvHwPjOvBycFAzqOGpSAjV0kCLqoAcCxfKu/FXOC0sWSKijyct3QO2GXN8Rdxq
  CODACY_PROJECT_TOKEN:
    secure: D6sKRVqmhLJMWCzVPIEAgR2maoBiMcoV2OT+m0Q1VP6UhAv/A2c7PWOyeqi2LPKp
  matrix:
    - PYTHON_TARGET: "py37"
    - PYTHON_TARGET: "py36"

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - pip install tox-conda

build: false

test_script:
  - tox -e %PYTHON_TARGET%
