environment:

  global:
    PIP_DEPENDENCIES: "tox-conda"

  matrix:
    - PYTHON_VERSION: "3.7"
    - PYTHON_VERSION: "3.6"

platform:
    - x64

install:
    - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

build: false

test_script:
  - "tox"