environment:
  secure: md7hB2z4rsebCwlPWEhDTGbOs4ppgBwsJcQkGygKJ91WlHN2V/HxrOyZlJ9fsZoJgwQdS2Fg5IDxGv/yPiuGDw==
  secure: PRspf+43tXnRJnVRpGeQPsL6/+fDxOIpSqfxmai8Qjp6q9maEtHbVbNW9w/Tsx2a
  matrix:
    - PYTHON_TARGET: "3.7"
    - PYTHON_TARGET: "3.6"

install:
  - set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n test-environment python=%PYTHON_TARGET% openbabel rdkit -c openbabel -c conda-forge
  - activate test-environment
  - pip install . pytest-sugar pytest-cov coveralls codecov>=1.4.0 codacy-coverage

build: false

test_script:
  - pytest --pyargs reacnetgenerator --cov -s
  - coveralls
  - codecov -e TOXENV
  - python-codacy-coverage -r coverage.xml
