environment:
  matrix:
    - TOX_ENV: "py37"
    - TOX_ENV: "py36"

install:
  - set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
  - pip install tox-conda

build: false

test_script:
  - tox -e %TOX_ENV%